CUDA_VISIBLE_DEVICESS=0 python evaluate.py \
--data-path ./data/minif2f_lean4_v4.10.0/default/ \
--prover MCTS_Reranker \
--model_name reprover \
--ckpt_path "kaiyuy/leandojo-lean4-tacgen-byt5-small" \
--reward_model_path ./ATP_vf \
--split test \
--num-cpus 1 \
--with-gpus \
--num-theorems 244 \
--num-sampled-tactics 64 \
--exp-id "minif2f" \
--k 48 \
--timeout 600  \
--iteration 100